### ISSUE TITLE
No matching distribution in python 3.10

### ISSUE THREAD

**Issue by fcossio** [InsightSoftwareConsortium/ITKIOFDF#38]
Hi, I am trying to install the python package but it seems that there is no distribution for python 3.10 pip 22.1.2. I am trying in a Windows10 OS the following:

```
$ pip --version
pip 22.1.2 from C:\Users\xxxxx\Miniconda3\envs\xx\lib\site-packages\pip (python 3.10)
$ pip install itk-io-fdf
ERROR: Could not find a version that satisfies the requirement itk-io-fdf (from versions: none)
ERROR: No matching distribution found for itk-io-fdf
```

However it is possible to install in python 3.6

**Comment by thewtex** [comment]
Hi,

Cross-platform Python packages for Python versions 3.8+ are now available with version 1.1.0.
